import { Inter } from "next/font/google";
import "./globals.css";
import NavigationMenubar from "@/components/NavigationMenuBar/NavigationMenubar";
import ToasterContext from "@/context/ToasterContext";
import SessionProvider from "@/context/AuthContext";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <NavigationMenubar />
          {children}
          <ToasterContext />
        </SessionProvider>
      </body>
    </html>
  );
}
